databases:
  - name: django-render-project
    databaseName: django_dbname
    user: vokur

services:
  - type: web
    name: django-render-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django-render-project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-render-project
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4